config/routes.rb
Gritter::Application.routes.draw do
  resources :grits
  resources :sessions, only: [:new, :create, :destroy]
  resources :registrations, only: [:new, :create]
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      post 'follow', as: 'follow'
      delete 'unfollow', as: 'unfollow'
    end
    collection do
      get 'recommended', as: 'recommended'
    end
  end

  get 'sign_in', to: 'sessions#new', as: 'sign_in'
  get 'sign_out', to: 'sessions#destroy', as: 'sign_out'

  root to: 'grits#index'

end

app/models/credential.rb
require 'bcrypt'

class Credential < Neo4j::Rails::Model

  attr_accessor :password

  property :password_salt, type: String
  property :password_hash, type: String
  property :updated_at
  property :created_at

  has_one(:owner).to(User)

  validates :password_salt, presence: true
  validates :password_hash, presence: true
  validates :password, presence: true, on: :save
  validates :password, confirmation: true, length: {minimum: 8}, if: :password?

  before_validation :encrypt_password

  def authenticated_with?(pw)
    return false if pw.blank?
    BCrypt::Engine.hash_secret(pw, self.password_salt) == self.password_hash
  end


  private

  def encrypt_password
    if password?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def password?
    self.password.present?
  end

end

app/models/grit.rb
class Grit < Neo4j::Rails::Model

  property :body, type: String, index: :fulltext
  property :created_at

  has_one(:author).to(User)
  has_one(:previous).to(Grit)
  has_one(:next).from(Grit, :previous)

  validates :body, presence: true, length: {in: 1..140}

end

app/models/registration.rb
class Registration
  include Virtus

  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_reader :user

  attribute :username, String
  attribute :name, String
  attribute :password, String
  attribute :password_confirmation, String

  validates :username, presence: true, length: {in: 1..20}
  validates :name, presence: true, length: {in: 1..50}
  validates :password, confirmation: true, length: {minimum: 8}

  # Forms are never themselves persisted
  def persisted?
    false
  end

  def save
    if valid?
      persist!
      true
    else
      false
    end
  end

  private

  def persist!
    @user = User.new(username: username, name: name)
    @credential = @user.build_credential(password: password, password_confirmation: password_confirmation)
    @user.save!
  end
end

app/models/user.rb
class User < Neo4j::Rails::Model

  property :username, type: String, index: :exact
  property :name, type: String, index: :fulltext
  property :bio, type: String
  property :updated_at
  property :created_at

  has_one(:credential).from(Credential, :owner)
  has_n(:grits).from(Grit, :author)
  has_one(:latest_grit).to(Grit)

  has_n(:following).to(User)
  has_n(:followers).from(User, :following)

  validates :username, presence: true, length: {in: 1..20}
  validates :name, presence: true, length: {in: 1..50}

  def avatar_url(size=80)
    "https://secure.gravatar.com/avatar/#{avatar_hash}?f=y&d=wavatar&s=#{size}"
  end

  # START v=node:User_exact("username:greg")
  # MATCH v-[:`User#following`]->(friend)-[:`User#following`]->(foaf)
  # WHERE NOT(v-[:`User#following`]->foaf) AND v <> foaf
  # RETURN distinct(foaf.username) as recommended, count(friend) as score, collect(friend.username) as followed_by
  # ORDER BY score DESC
  def get_recommended_users
    Neo4j.query(self) { |u|
      u > User.following > node(:friend) > User.following > :foaf
      where_not{ u > User.following > :foaf }
      where{ u != :foaf }
      ret(
        node(:foaf).distinct.as(:recommended).limit(25),
        node(:friend).count.as(:score).desc,
        node(:friend)[:username].collect.as(:followed_by)
      )
    }.map{|row|
      recommended = row[:recommended]
      recommended[:followed_by] = row[:followed_by].to_a.sample(3).map{|un| User.find(username: un) }
      recommended[:total_followed_by] = row[:followed_by].count - recommended[:followed_by].count
      recommended
    }
  end

  def timeline
    grits = Neo4j.query(self){ |u|
      u > User.following > node(:followed) < Grit.author < node(:g).desc(:created_at).limit(25)
      ret(:g)
    }.map{|res| res[:g] }

    if grits.empty?
      grits = Grit.find(:all).take(50)
    end

    grits
  end

  def full_timeline
    theirs = timeline

    (theirs + self.grits).sort_by(&:created_at).reverse.take(25)
  end

  private

  def avatar_hash
    Digest::MD5.hexdigest(username)
  end

end

app/models/user_authenticator.rb
class UserAuthenticator
  def self.authenticate(username, password)
    user = User.find(username: username)
    if user && user.credential.authenticated_with?(password)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  def current_user
    @current_user ||= User.find(username: session[:username]) if session[:username]
  end

  def require_login
    redirect_to new_session_path, alert: 'You must login to continue.' unless current_user
  end
end

app/controllers/grits_controller.rb
class GritsController < ApplicationController
  before_filter :require_login

  def index
    @grits = current_user.full_timeline
  end

  def show
    @grit = Grit.find(params[:id])
  end

  def new
    @grit = Grit.new
  end

  def create
    @grit = current_user.grits.build(params[:grit].slice(:body))
    @grit.previous = current_user.latest_grit
    current_user.latest_grit = @grit
    if @grit.save && current_user.save
      render :show
    else
      render :new
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @registration = Registration.new
  end

  def create
    @registration = Registration.new(params[:registration])
    if @registration.save
      session[:username] = @registration.username
      flash[:notice] = "Account created. Welcome #{@registration.name}!"
      redirect_to root_path
    else
      @registration.password = nil
      @registration.password_confirmation = nil
      render :new
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = UserAuthenticator.authenticate(params[:user][:username], params[:user][:password])
    if user
      session[:username] = user.username
      flash[:notice] = "Login successful."
      redirect_to root_path
    else
      @user = User.new(username: params[:username])
      flash[:alert] = "Login failed. Please check your username and password again."
      render :new
    end
  end

  def destroy
    session[:username] = nil
    @current_user = nil
    flash[:notice] = "Logout successful."
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  class SelfFollowException < Exception; end
  class AlreadyFollowingException < Exception; end
  class NotFollowingException < Exception; end

  respond_to :html, :json

  before_filter :require_login, except: [:index]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @grits = @user.grits.sort_by(&:created_at)
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user].slice(:name, :bio))
      flash[:notice] = "Successfully updated your profile."
      redirect_to :show
    else
      flash[:alert] = "Oh no! Something went wrong. Please try again."
      render :edit
    end
  end

  def follow
    follower = current_user
    followee = User.find(params[:id])

    raise SelfFollowException if follower == followee
    raise AlreadyFollowingException if followee.followers.include?(follower)

    # I'd love to use:
    # Neo4j.query(follower, followee) do |me, them|
    #   create_unique_path{ me > User.following > them }
    # end

    followee.followers << follower
    followee.save
    respond_with followee
  end

  def unfollow
    follower = current_user
    followee = User.find(params[:id])

    raise SelfFollowException if follower == followee
    raise NotFollowingException unless followee.followers.include?(follower)

    followee.followers.delete(follower)
    followee.save
    respond_with followee
  end

  def recommended
    @users = current_user.get_recommended_users
    render :index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/grits/_form.html.slim
= form_for :grit, url: grits_url, method: :post do |f|

  .field
    = f.text_area :body, rows: 3, class: 'grit-body', placeholder: "What's up?"
    .actions.right= f.submit 'Grit It!', class: 'button'
    .counter
      span.count
        '140 
      | characters remaining

app/views/grits/_grit.html.slim
.row
  .vertical-list-item.grit
    = link_to user_path(grit.author)
      .avatar= image_tag grit.author.avatar_url(90)
    = render partial: 'users/username', locals: { user: grit.author}
    .body= grit.body
    .timestamp= link_to grit.created_at.stamp('Jan 22nd 5:13pm'), grit_path(grit)

app/views/grits/index.html.slim
.new-grit
  = render partial: 'grits/form'

.vertical-list
  = render partial: 'grits/grit', collection: @grits

app/views/grits/new.html.slim
h3 New Grit

= render partial: 'grits/form'

app/views/grits/show.html.slim
.main
  = render partial: 'grits/grit', locals: {grit: @grit}

.related
  - if @grit.next.present?
    .next
      h4 Next Grit
      = render partial: 'grits/grit', locals: {grit: @grit.next}
  - if @grit.previous.present?
    .prev
      h4 Previous Grit
      = render partial: 'grits/grit', locals: {grit: @grit.previous}

app/views/layouts/application.html.slim
doctype html
head
  meta charset="utf-8"
  meta name="viewport" content="width=device-width, initial-scale=1.0"
  title= content_for?(:title) ? yield(:title) : "Gritter"
  = stylesheet_link_tag "application"
  = javascript_include_tag "application"
  = csrf_meta_tag

body.gritter

  .row.nav-row
    nav.top-bar.constrain-to-grid
      ul.title-area
        li.name
          h1= link_to 'Gritter', root_path

      section.top-bar-section
        ul.left
          li.divider
          li= link_to 'Timeline', grits_path
          li= link_to 'Users', users_path
          li= link_to 'Recommended Users', recommended_users_path if current_user && current_user.following.count > 0

      section.top-bar-section
        ul.right
          - if current_user
            li= link_to 'Edit Profile', edit_user_path(current_user)
            li.divider
            li= link_to 'Sign Out', sign_out_path
          - else
            li= link_to 'Sign In', sign_in_path
            li= link_to 'Sign Up', new_registration_path

  .row
    .backer.columns.large-12
      - unless flash.empty?
        .row
          .flash
            - flash.each do |type, msg|
              div(class="alert-box #{type}" data-alert)
                = msg
                = link_to '#', class: 'close' do
                  '&times;

      .row
        == yield

app/views/users/_follow_button.html.slim
- size ||= ''

- unless current_user == user
  - following = user.followers.include?(current_user)

  .follow-button(class="user-#{user.id}")
    .follow(class=size style="display: #{following ? 'none' : 'block'};")
      = link_to 'Follow', follow_user_path(user, :json), method: :post, remote: true
    .unfollow(class=size style="display: #{following ? 'block' : 'none'};")
      = link_to 'Unfollow', unfollow_user_path(user, :json), method: :delete, remote: true

app/views/users/_user.html.slim
.row
  .vertical-list-item.user

    = link_to user_path(user)
      .avatar= image_tag user.avatar_url(90)

    = render partial: 'users/username', locals: { user: user}

    .followers
      'Followers: 
      = user.followers.count

    .following
      'Following: 
      = user.following.count

    .follow-container= render partial: 'users/follow_button', locals: { user: user, size: 'small' }

    - if user[:followed_by].present?
      .followed-by
        'Followed by:
        ul
          - user[:followed_by].each do |follower|
            li= link_to follower.username, follower
        | and #{user[:total_followed_by]} others.

    .bio= simple_format user.bio

app/views/users/_username.html.slim
= link_to user_path(user)
  .username
    | @
    = user.username
    | &nbsp;&nbsp;
    span.name
      | (
      = user.name
      |)

app/views/users/edit.html.slim
h3 Edit Your Profile

= form_for :user, url: user_path(@user), method: :put do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} errors were found:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :bio
    = f.text_area :bio, rows: 3

  .actions = f.submit 'Update'

app/views/users/index.html.slim
.vertical-list
  = render partial: 'users/user', collection: @users

app/views/users/show.html.slim
.row
  .large-3.columns.large-offset-2
    = image_tag @user.avatar_url(150)

  .large-5.columns
    h3= render partial: 'users/username', locals: { user: @user}
    p= simple_format @user.bio if @user.bio.present?
    = render partial: 'users/follow_button', locals: { user: @user }

  .large-2.columns

.row
  .vertical-list
    = render partial: 'grits/grit', collection: @grits